// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function map(f, source, start, sink) {
  if (start !== 0) {
    return ;
  } else {
    return Curry._2(source, start, (function (t, d) {
                  return Curry._2(sink, t, t === 1 ? Curry._1(f, d) : d);
                }));
  }
}

exports.map = map;
/* No side effect */
